version: "3.8"
 
services:
  app:
    container_name: app
    restart: always
    image: myapp
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
